AcunRedMain/AcunRedMain/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path



urlpatterns = [
    path("admin/", admin.site.urls),
    path("polls/", include("polls.urls")),
    path("voting/", include("voting.urls")),
    
]

AcunRedMain/api/urls.py
from django.urls import path
from . import views

AcunRedMain/polls/urls.py
from django.urls import path
from . import views

app_name = "polls"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:question_id>",views.detail,name="detail"),
    path("<int:question_id>/results",views.results,name="results"),
    path("<int:question_id>/vote",views.vote,name="vote")
    
]

AcunRedMain/voting/urls.py
from django.urls import path
from . import views
from django.contrib.auth.urls import views as auth_views

app_name = "votings"
urlpatterns = [
    path("",views.index,name="index"),
    path("<int:post_id>",views.detail,name="detail"),
    path("<int:post_id>/results",views.results,name="results"),
    path("<int:post_id>/vote",views.vote,name="vote"),
    path("<int:post_id>/comment",views.comment,name="comment"),
    path("<int:post_id>/comment/<str:comment_text>",views.add_comment,name="comment"),
    path("login",views.login_view,name="login_view")
]

AcunRedMain/api/models.py
from django.db import models

# Create your models here.

AcunRedMain/polls/models.py
import datetime
from django.db import models
from django.utils import timezone
# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    
    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete = models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text
    

AcunRedMain/voting/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    post_text = models.CharField(max_length=200)
    pub_date =  models.DateTimeField("date published")
    def __str__(self):
        return self.post_text

class Choice(models.Model):
    question = models.ForeignKey(Post, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text
    
class Comment(models.Model):
    question = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

AcunRedMain/api/views.py
from django.shortcuts import render
from rest_framework import viewsets
from rest_framework.response import Response

# Create your views here.

class LoginViewSet(viewsets.ModelViewSet):
    serializer_class = UserSerializer

    def login(self, request):
        # Get the username and password from the request
        username = request.data['username']
        password = request.data['password']

        # Authenticate the user
        user = authenticate(username=username, password=password)

        # If the user is authenticated, return a success response
        if user is not None:
            return Response({'success': True, 'user': user.username})

        # If the user is not authenticated, return a failure response
        else:
            return Response({'success': False, 'error': 'Invalid username or password'})

AcunRedMain/polls/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Question
from django.template import loader
from django.http import Http404


# Create your views here.
def index(request):
    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    template = loader.get_template("polls/index.html")
    context = {
        "latest_question_list": latest_question_list,
    }
    return HttpResponse(template.render(context, request))

def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, "polls/detail.html", {"question": question})

def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

AcunRedMain/voting/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Post,Choice
from django.http import Http404
from django.template import loader
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    latest_post_list = Post.objects.order_by("-pub_date")[:5]
    template = loader.get_template("voting/index.html")
    context = {
        "latest_post_list": latest_post_list,
    }
    return HttpResponse(template.render(context, request))



def detail(request, post_id):
    try:
        post = Post.objects.get(pk=post_id)
    except Post.DoesNotExist:
        raise Http404("post does not exist")
    print("----------------------")
    print("----------------------")
    return render(request, "voting/detail.html", {"post": post})

def results(request, post_id):
    response = "You're looking at the results of post %s."
    return HttpResponse(response % post_id)

def vote(request, post_id):
    if not request.user.is_authenticated:
        return HttpResponse("You are not logged in")
    return HttpResponse("You're voting on post %s." % post_id)

@login_required(login_url="/voting/login")
def comment(request, post_id):
    return HttpResponse("You're commeting on post %s." % post_id)

def add_comment(request, post_id,comment_text):
    if not request.user.is_authenticated:
        return HttpResponse("You are not logged in")
    return HttpResponse("added comment %s." % comment_text)

def login_view(request):
    #username = request.POST["jack"]
    #username = "jack"
    #password = "123"
    username = request.POST["username"]
    password = request.POST["password"]
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        return HttpResponse("success")
    else:
        return HttpResponse('invalid login' )
        

AcunRedMain/polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>{{ question.question_text }}</h1>
    <ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }}</li>
    {% endfor %}
    </ul>
</body>
</html>

AcunRedMain/polls/templates/polls/index copy.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>{{ question.question_text }}</h1>
    <ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }}</li>
    {% endfor %}
    </ul>
</body>
</html>

AcunRedMain/polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</body>
</html>

AcunRedMain/voting/templates/voting/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>"IDEA:"{{ post.post_text }}</h1>
    <ul>
    {% for choice in post.choice_set.all %}
        <li>option :{{ choice.choice_text }}</li>
        <ul>
            <li>"votes":{{ choice.votes }}</li>
        </ul>
    {% endfor %}
    </ul>
</body>
</html>

AcunRedMain/voting/templates/voting/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>I like trains</title>
</head>
<body>
    {% if latest_post_list %}
    <ul>
    {% for post in latest_post_list %}
    <li> "IDEA:" <a href="{% url 'votings:detail' post.id %}">{{ post.post_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No posts are available.</p>
{% endif %}
</body>
</html>